---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-prometheus-monitoring
  namespace: ml-workshop
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - services
      - endpoints
      - pods
  - verbs:
      - get
    apiGroups:
      - '*'
    resources:
      - configmaps

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-monitoring-view
rules:
- apiGroups:
  - "*"
  resources:
  - namespaces
  - statefulsets
  verbs:
  - get      